services:
  - type: web
    name: horse-betting-backend
    env: python
    runtime: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
